name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: "Samiran2004"  # Replace this with your actual GitHub username
          outputs: ./dist/snake.svg
