name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: "Samiran2004"  # Replace with your GitHub username
          outputs: dist/snake.svg

      - name: Push generated animation
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: output
          force: true
          directory: dist
